services:
  postgresql:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: prever_user
      POSTGRES_PASSWORD: prever_pass
      POSTGRES_DB: prever_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    command: >
      postgres
      -c max_connections=600
      -c shared_buffers=512MB
      -c effective_cache_size=768MB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=8MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c max_wal_size=2GB
      -c min_wal_size=1GB
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tranx.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
volumes:
  postgres_data: